// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2KhdPSkAFuWCPG4nFheV9cO-ImZoKAFQ',
    appId: '1:295665758504:web:685ebd67ffaf7b843f601d',
    messagingSenderId: '295665758504',
    projectId: 'tasks-cpf-laith',
    authDomain: 'tasks-cpf-laith.firebaseapp.com',
    storageBucket: 'tasks-cpf-laith.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl8gcz_o1aApW4loUBydw2BI8sQ1HqkVQ',
    appId: '1:295665758504:android:8805dc541bd047653f601d',
    messagingSenderId: '295665758504',
    projectId: 'tasks-cpf-laith',
    storageBucket: 'tasks-cpf-laith.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtjNv9xXVnl9YgJG9O8olFzmKYxkyi5qM',
    appId: '1:295665758504:ios:4a6975cd95cf392e3f601d',
    messagingSenderId: '295665758504',
    projectId: 'tasks-cpf-laith',
    storageBucket: 'tasks-cpf-laith.firebasestorage.app',
    iosBundleId: 'com.example.tasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtjNv9xXVnl9YgJG9O8olFzmKYxkyi5qM',
    appId: '1:295665758504:ios:4a6975cd95cf392e3f601d',
    messagingSenderId: '295665758504',
    projectId: 'tasks-cpf-laith',
    storageBucket: 'tasks-cpf-laith.firebasestorage.app',
    iosBundleId: 'com.example.tasks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2KhdPSkAFuWCPG4nFheV9cO-ImZoKAFQ',
    appId: '1:295665758504:web:a96e2c22c81437ce3f601d',
    messagingSenderId: '295665758504',
    projectId: 'tasks-cpf-laith',
    authDomain: 'tasks-cpf-laith.firebaseapp.com',
    storageBucket: 'tasks-cpf-laith.firebasestorage.app',
  );
}
